#!/bin/bash
set -eu
set -o pipefail

# Set lower key delay interval to speed up boot command typing
export PACKER_KEY_INTERVAL="10ms"

# Set packer cache to default if not specified
PACKER_DEFAULT_CACHE_DIR=${HOME:-/tmp}/.packer_cache
export PACKER_CACHE_DIR="${PACKER_CACHE_DIR:-${PACKER_DEFAULT_CACHE_DIR}}"

# Parse command line arguments
ARGS="${@:1:($#-1)}" # packer command and arguments starting with "-" or "--", e.g. 'build --only=qemu'
TEMPLATE_PATH="${@:$#}" # full path to packer JSON template file name

# Check provided template argument
if [ -z ${TEMPLATE_PATH} ] || [ ! -f ${TEMPLATE_PATH} ]; then
  packer ${ARGS}
  exit 1
fi

# Run packer
cd $(dirname ${TEMPLATE_PATH})
(packer ${ARGS} <(jsmin <$(basename ${TEMPLATE_PATH})))
cd - > /dev/null
